# Generated by Django 5.1.1 on 2024-12-14 19:05

import rosstat.backend_storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfile',
            name='file',
            field=models.FileField(storage=rosstat.backend_storages.YandexStorage(), upload_to='', verbose_name='Файл'),
        ),
    ]
