# Generated by Django 5.1.1 on 2024-12-14 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_files', '0002_alter_userfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfile',
            name='created_exp',
            field=models.DateTimeField(verbose_name='Дата создания'),
        ),
    ]
