# Generated by Django 5.1.1 on 2024-12-14 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_size', models.IntegerField(default=5, verbose_name='Максимальный размер файла в мегабайтах')),
                ('file_lifetime_seconds', models.IntegerField(default=2678400, verbose_name='Время жизни файла в секундах')),
            ],
            options={
                'verbose_name': 'Глобальные настройки',
                'verbose_name_plural': 'Глобальные настройки',
                'db_table': 'global_settings',
            },
        ),
    ]
