# Generated by Django 5.1.1 on 2024-12-14 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileExtension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extension', models.CharField(choices=[('zip', 'zip'), ('rar', 'rar'), ('7z', '7z'), ('tar', 'tar'), ('gz', 'gz'), ('csv', 'csv'), ('xls', 'xls'), ('xlsx', 'xlsx'), ('doc', 'doc'), ('docx', 'docx'), ('ppt', 'ppt'), ('pptx', 'pptx'), ('txt', 'txt'), ('pdf', 'pdf'), ('json', 'json'), ('xml', 'xml'), ('html', 'html'), ('css', 'css'), ('js', 'js'), ('sql', 'sql'), ('md', 'md'), ('png', 'png'), ('jpg', 'jpg'), ('jpeg', 'jpeg'), ('gif', 'gif'), ('bmp', 'bmp'), ('tiff', 'tiff'), ('ico', 'ico'), ('xml', 'xml'), ('svg', 'svg'), ('mp3', 'mp3'), ('wav', 'wav'), ('ogg', 'ogg'), ('aac', 'aac'), ('flac', 'flac')], max_length=4, verbose_name='Расширение файла')),
            ],
            options={
                'verbose_name': 'Расширение файла',
                'verbose_name_plural': 'Расширения файлов',
                'db_table': 'file_extension',
            },
        ),
    ]
