# Generated by Django 5.1.1 on 2024-12-14 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_settings', '0002_fileextension'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='url_lifetime_seconds',
            field=models.IntegerField(default=3600, verbose_name='Время жизни ссылки в секундах'),
        ),
    ]
